### ISSUE TITLE
Recommandation about Wapiti usage

### ISSUE THREAD

**Issue by devl00p** [wapiti-scanner/wapiti#104]
One suggestion : I might have missed it, but I could not see any mention regarding the fact that real POST with real test content about ... everywhere. For systems like CMS or Blogs, one could end-up with a website with a configuration pretty much messed-up. So something like  /!\ do not use on a production system /!\ might come handy. I think.

_Originally posted by @superseby2 in https://github.com/wapiti-scanner/wapiti/issues/103#issuecomment-814112298_

**Comment by devl00p** [comment]
Todo: add an entry in FAQ about not using production website to launch Wapiti and the fact it may be useful to remove newly injected comments ( `Hi there`) from a database.

**Comment by superseby2** [comment]
Also an entry about : make sure you have a backup of your DB before running Wapiti (because, not only comments are injected, my site for instance went in maintenance mode and changed the Google Analytics tracking code and replace it with Hi There ;)). Sochanges are everywhere and would be hard to revert manually.

**Comment by tarraschk** [comment]
Regarding this issue, I suggest to add something like a disclaimer instead of writing "do not use this on a production system". Indeed, such phrasing could lead to the feeling that the project is not "production-ready" instead of telling people to be careful.

I suggest instead to just add something in the README.md like:

```markdown
### Disclaimer

Wapiti is a cybersecurity software. It performs security assessments on a provided target, which can lead to malfunctions and crashes on the target, as well as potential data loss.

Usage of Wapiti for attacking a target without prior consent of its owner is illegal. It is the end user's responsibility to obey all applicable local laws.

Developers and people involved in the Wapiti project assume no liability and are not responsible for any misuse or damage caused by this program.
```

Would that be okay for you? If so I'll make the PR
