### ISSUE TITLE
DVWA Testing

### ISSUE THREAD

**Issue by grandtom** [wapiti-scanner/wapiti#106]
Hi team,

I've tried to use for the first time Wapiti on DVWA https://dvwa.co.uk/. 

I'm not sure to use it correctly but Wapiti didn't find any XSS on /vulnerabilities/xss_r/. There is a XSS on name parameter: /vulnerabilities/xss_r/?name=

What can I do to help Wapiti finding this XSS ?

**Comment by bretfourbe** [comment]
Hi @grandtom,
Please, can you give the command you are using for your scan ?
Maybe it is due to the security level on your DVWA, by default it is set to "impossible".

**Comment by grandtom** [comment]
Hi @bretfourbe,

Here is the command : 
`wapiti -u http://localhost:80/ -c cookie.json -m xss -S insane -v 2`

My DVWA security level is low, that's why I am really surprised.

![image](https://user-images.githubusercontent.com/35311255/114020214-a3b0d900-986f-11eb-9a8b-3136cb290491.png)

**Comment by bretfourbe** [comment]
@grandtom Ok, please make sure the session cookie in cookie.json is valid. If you have the last version from github master you also can try using `-c chrome` or `-c firefox` for instance to use the cookies from your browser. Make sure to exclude the logout URL using `-x/--exclude`option.
On my side, I  still do not know why, the wapiti-getcookie provide a session cookie which is not valid for dvwa.

**Comment by grandtom** [comment]
Thank you @bretfourbe. `-c chrome` or `-c firefox` seems to be a great feature. Unfortunately, I use wapiti 3.0.4 (with pip install). Can i hope an update soon ?

**Comment by bretfourbe** [comment]
@grandtom in that case you can edit the cookie.json with a valid session cookie to make it works for now.
I don't know for update. But maybe you can clone the github repo to use the latest version.

**Comment by grandtom** [comment]
Hi @bretfourbe, with your recommandation, it seems to be better. But wapiti do not see anything:

<img width="1237" alt="Capture d’écran 2021-04-09 à 14 12 10" src="https://user-images.githubusercontent.com/35311255/114178305-d6290780-993d-11eb-93f7-c8c152997879.png">

Is it the same on your side ?

**Comment by bretfourbe** [comment]
@grandtom on my side it happens only if the security level is set to "impossible". XSS should be detected even if security level is "hard".

**Comment by OussamaBeng** [comment]
@grandtom in the interactive terminal make sure you copy/past the value of "Login" and "user_token" because wapiti-getcookie doesn't take those value by default ... That's why your cookie isn't valid and wapiti can't detect any vulnerability 
![image](https://user-images.githubusercontent.com/58309137/114217378-5cf2da00-9968-11eb-831a-bc8c1e2c6bfe.png)

I modified the wapiti-get cookie to thale this values by default .. It will be merged soon ;)

**Comment by grandtom** [comment]
Thank you @OussamaBeng.

Would someone have a capture showing that wapiti detects the reflected XSS (with Security level = low) ?

When Wapiti tries: 
`http://localhost:80/vulnerabilities/xss_r/?name=%3CScRiPt%3Ealert%28%27wvyxzs2jpj%27%29%3C%2FsCrIpT%3E`
DVWA returns in an HTML page :
```
Hacking attempt detected and logged.
Have a nice day.
```
For Wapiti => No XSS

**Comment by OussamaBeng** [comment]
@grandtom I just tried it and the XSS is detected 
![image](https://user-images.githubusercontent.com/58309137/114235142-0a251c80-9980-11eb-86cb-dc95f73c635f.png)
And this is the report 
![image](https://user-images.githubusercontent.com/58309137/114235283-40629c00-9980-11eb-9731-3ed8678284e3.png)

**Comment by grandtom** [comment]
Hi @OussamaBeng, 

Thank you. I managed to display the XSS, but I have a strange behavior.

I launch the scanner a first time  and the result is correct.

<img width="1427" alt="Capture d’écran 2021-04-10 à 10 25 28" src="https://user-images.githubusercontent.com/35311255/114263637-1b554400-99e7-11eb-8784-8c51a5839568.png">

I run the scanner a second time a few seconds later with the same parameters and the result is incorrect.

<img width="1395" alt="Capture d’écran 2021-04-10 à 10 27 12" src="https://user-images.githubusercontent.com/35311255/114263673-55264a80-99e7-11eb-9d91-4d8eb3265748.png">

It's strange. Wapiti logo do not look the same.

Any idea ?

**Comment by devl00p** [comment]
Mystery solved

I was able to reproduce the issue the docker image for dvwa.

The problem is that the crawler will fetch the URL `http://127.0.0.1/security.php?phpids=on` which activates phpids :stuck_out_tongue_closed_eyes: 

So when Wapiti try to perform the XSS it receives the message `Hacking attempt detected and logged.` instead of having reflected XSS.

Excluding the `security.php` URL fixes that:

`./bin/wapiti -u http://127.0.0.1/ -s http://127.0.0.1/vulnerabilities/xss_r/ -x http://127.0.0.1/logout.php -c /tmp/cookies.json -m xss -v2 --color --flush-session -x "http://127.0.0.1/security.php*"`
