### ISSUE TITLE
Many network issues identified during scans

### ISSUE THREAD

**Issue by bretfourbe** [wapiti-scanner/wapiti#394]
Hi @devl00p !
I observed that many network issues are raised during scans, on several modules (ssrf, file, buster, crlf, log4shell).
I changed the code in a module (buster in this case) to get the stack traces below.
On HTTP target (testphp.vulweb.com) :
![image](https://user-images.githubusercontent.com/27951656/233299368-cb3f41b1-a526-4de3-90cf-95cc3d361ef4.png)
![image](https://user-images.githubusercontent.com/27951656/233299983-5afbedb3-7874-4164-bbd4-b51641d53040.png)
On HTTPS target : 
![image](https://user-images.githubusercontent.com/27951656/233302538-b73d99b8-d22f-429f-af2c-404d78942a22.png)
![image](https://user-images.githubusercontent.com/27951656/233302699-2f033a2a-3bd3-42e4-acdf-addd44c6cd53.png)
Do you have any idea ?
Thanks !

**Comment by tarraschk** [comment]
@devl00p pour information on a rencontré à nouveau ce type de souci sur d'autres sites

On va t'envoyer le tout par email séparé, mais on aurait besoin d'un coup de main sur ce ticket

**Comment by Darkiros** [comment]
Hi all, 

I think I have identified the problem.
In my opinion, it comes from the global tiemout.
If you do the command `wapiti -u "[ANY SITE]" -m "" --flush-session -t 30 -v2` there is no network issue.

To fix the problem I changed these lines in `crawler.py`: 

https://github.com/wapiti-scanner/wapiti/blob/master/wapitiCore/net/crawler.py#L154C1-L165C78

```python
        client = httpx.AsyncClient(
            auth=auth,
            headers=headers,
            cookies=configuration.cookies,
            verify=ssl_context,
            proxies=cls._proxy_url_to_dict(configuration.proxy),
            timeout=configuration.timeout,
            event_hooks={"request": [drop_cookies_from_request]} if configuration.drop_cookies else None,
        )


        client.max_redirects = 5
        return cls(configuration.base_request, client, configuration.timeout)
```

* `timeout = configuration.timeout` -> `timeout = None`
* `return cls(configuration.base_request, client, configuration.timeout)` -> `return cls(configuration.base_request, client, None)`

I think we can do that better with something like
```python
timeout = httpx.TimeoutConfig(connect_timeout=5, read_timeout=[ANY TIME YOU WANT], write_timeout=5)
response = httpx.get('[ANY SITE]', stream=stream, timeout=timeout)
```

I think it should fix our problem because is focus on the response timeout.

@devl00p

**Comment by devl00p** [comment]
The default timeout is certainly too low. In `Wapiti.set_timeout` and in the command line parser the default is 6 seconds.

The default timeout used by w3af is 15s while it is 30s for sqlmap.

I think it would be nice to increase the default value to at least 10 but not more than 15.

For the headless cases it may be related to mitmproxy being slow. Unfortunately that tool lacks some options to tweak performance

**Comment by tarraschk** [comment]
OK so from my understanding and based on my discussion with @Darkiros, in order to not make everything too complex, and to still keep compatibility with the `-t`parameter:

1. We could change the default timeout value to a more complex structure like this:

```
timeout = httpx.TimeoutConfig(connect_timeout=5, read_timeout=10, write_timeout=5)
```

@Darkiros told me that the issue might be more linked to the `read_timeout` as we do not have enough time to parse the response of some websites, but the connection is actually okay on the same website. That's why we increase this value only.

Another approach would be using a common default value set at 10 secondes on all fields if it's easier / better.

2. If people use the `-t` then we use their provided value for timeout, on all fields (default behavior of httpx timeout when provided with only one value)

What do you think?

**Comment by devl00p** [comment]
I agree, the timeout value should be applied to all types of timeout
