### ISSUE TITLE
Issue 500 for OWASP benchmark

### ISSUE THREAD

**Issue by sammy2201** [wapiti-scanner/wapiti#414]
I'm trying to run Wapiti against the OWASP Benchmark, but I'm encountering an error 500. Can anyone help me troubleshoot this issue?

Could someone provide assistance in resolving this error?
![IMG_8392](https://github.com/wapiti-scanner/wapiti/assets/68069107/c0e26209-5c0f-4ea1-b49b-4ce355643c07)

**Comment by tarraschk** [comment]
Hey @sammy2201 if you receive 500 errors, it means that the targeted website crashes when Wapiti performs its injections.

I'd definitely check your website logs for that, in order to see what crashes, but it's not related to the Wapiti project.

**Comment by sammy2201** [comment]
> but it's not related to the Wapiti project

I appreciate your suggestion regarding checking the website logs. However, I have confirmed that the website is functioning properly. Before using Wapiti, I actually conducted a scan using OWASP ZAP, and the scan results were generated successfully.

Could you please provide further assistance in troubleshooting the error 500 I encountered when running Wapiti against the OWASP Benchmark?

**Comment by tarraschk** [comment]
@sammy2201 as mentioned in my previous comment, I suggest that you check your website logs

You should look for the error log file, and look at which requests generated by Wapiti actually provoke the 500 error code.

Moreover, as described here https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500 a 500 error code means "Internal Server Error", implying that the problem is definitely on the server / website side, not on the Wapiti side here.
