### ISSUE TITLE
The Test " tests/endpoint/test_endpoint.py" on remote fail

### ISSUE THREAD

**Issue by OussamaBeng** [wapiti-scanner/wapiti#43]
Hi,
Considering that Python 3.5 is no longer supported since 13 september 2020.
![python_3-5_end_of_life](https://user-images.githubusercontent.com/58309137/103084083-638a5b00-45de-11eb-9810-e5193161e197.PNG)
We tried to edit the test part to exclude the version 3.5 from the tests because it causes an error when we execute "make test"
![python_3-5_error](https://user-images.githubusercontent.com/58309137/103084175-ad734100-45de-11eb-9987-4530ec3432cc.PNG)
There was 3 files to edit so that the tests exclude the Python 3.5 part.
![edited_file_1](https://user-images.githubusercontent.com/58309137/103084343-0e027e00-45df-11eb-809b-c6ef64f3dd66.PNG)

![edited_file_2](https://user-images.githubusercontent.com/58309137/103084358-16f34f80-45df-11eb-9dc5-568b2914dca4.PNG)

![edited_file_3](https://user-images.githubusercontent.com/58309137/103084373-1e1a5d80-45df-11eb-87f4-ddc1b4008431.PNG)
After the commit, we executed "make test" and all the tests passed with success 
![local_test](https://user-images.githubusercontent.com/58309137/103084447-473aee00-45df-11eb-8f72-12dd61aaaddf.PNG)

But on the file "tests/endpoint/test_endpoint.py" the test :
- "assert data["53"]["76756c6e"][0]["payload"] == "linux2" has fail on remote tests when you push a new commit
![remote_test](https://user-images.githubusercontent.com/58309137/103084542-8a955c80-45df-11eb-9048-8c0029fd6587.PNG)

The value of "assert data["53"]["76756c6e"][0]["payload"]" return "unknown" instead of "linux2"
![error_detail](https://user-images.githubusercontent.com/58309137/103084630-bca6be80-45df-11eb-90e9-515f5e636d07.PNG)

The problem is not ont the project's code, because all the tests in local pass with success.
We think that it cames from the Github actions so we would like to know your opinion about this error.

**Comment by tarraschk** [comment]
Hello @devl00p, je me permets de te tagger sur ce sujet pour que l'on ait ton avis :) 

Excellentes fêtes de fin d'année à toi et tes proches !

**Comment by devl00p** [comment]
Bonne année à tous :)

Fixed with latest commit ( https://github.com/wapiti-scanner/wapiti/commit/b00c08e6e5a4cbeffcbc6b8315b68724844b4766 )

The `xxe_store.php` script shoud have received the payload type as an int, not a string. `mod_xxe` was sending it the right way but not the test.

On the other site `xxe_store.php` was looking for a string instead of an int so I guess the result was instead of giving the used XXE payload in the report it was giving the placeholder ( https://github.com/wapiti-scanner/wapiti/blob/5b735312135c1cd9b30cd24e05d9086fb0a6e8ad/wapitiCore/attack/mod_xxe.py#L383 ) because it could not find the corresponding payload.
