### ISSUE TITLE
Flush-attack option not working or synopsis is not clear

### ISSUE THREAD

**Issue by Maselia464** [wapiti-scanner/wapiti#76]
Hello.

When I try to use: "wapiti -u [URL] --flush-attack it's start another scan

So maybe the flush attack option is broken or the Synopsis isn't clear for me.

Thank in advance

**Comment by bretfourbe** [comment]
Hi @Maselia464  ! 
Could you tell me what do you expect from this option ?
Flush attack option should be used when you have already launched attack modules on a target and you want to only delete attack results (and not the crawled urls) before starting attack modules for the current scan.
Ask if it is still not clear :)

**Comment by Maselia464** [comment]
I was expecting something like: Your url as been deleted and not wapiti to start the scan

**Comment by bretfourbe** [comment]
Ok, in that case try using `-m ""` option. No attack module will be launched. If `-m` is not specified, default attack modules are launched. See more here : [https://github.com/wapiti-scanner/wapiti/blob/master/doc/wapiti.ronn](https://github.com/wapiti-scanner/wapiti/blob/master/doc/wapiti.ronn).

**Comment by devl00p** [comment]
I fixed #79 that might be related to this behavior : the bug would have made Wapiti crawl the website again even if the scan was complete the previous time.

Still it is currently expected behavior that `flush-attacks` just erases the attack history and launches fresh attacks.

As @bretfourbe said you can still use `-m ""` to prevent attacks from being launched again.
