### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by Yvtq8K3n** [wapiti-scanner/wapiti#97]
I have been using wapiti for a while, however, I'm not entirely sure if wapiti can crawler Modern Web Applications that are based in Ajax. With the current interactions I had with the tool, it seems it doesn't but I wanted to be sure.

Regardless, does wapiti have the capability to send malicious JSON payloads? My current SQLiteDB, when crawls, doesn't have any POST requests so I can't be sure.

If it is possible how could I force wapiti to load the POST Request?
Sorry, for the questions but couldn't find anything on the wiki.

**Comment by bretfourbe** [comment]
Hi @Yvtq8K3n,
It is hard to deal with single page apps since wapiti does not behave like a proxy that intercepts the requests already forged by the frontend.
Work is in progress on that point to better crawl those apps.
POST requests are extracted from detected forms, and fields are not sent in JSON format and you cannot force wapiti to send JSON payloads for now.
But feel free to help on that :)

**Comment by devl00p** [comment]
There is support for custom content type requests within Wapiti but it is currently unused (except for the XXE module) because it lack mechanism to inject payloads in JSON variables (a JSON mutator) and also as @bretfourbe said there is currently no way of intercepting ajax requests (maybe one day using mitmproxy but it is currently unplanned).

**Comment by devl00p** [comment]
The mitmproxy support is included in the latest release. A headless browser support (with Firefox) is on its way.

I'm closing this issue and I will create one for the missing mutators.
