### ISSUE TITLE
Error downloading nikto database

### ISSUE THREAD

**Issue by xx132917** [wapiti-scanner/wapiti#98]
Problem with local nikto database.
Downloading from the web...
Error downloading nikto database.
Problem with local wapp database.
Downloading from the web...
Error downloading wapp database.

**Comment by bretfourbe** [comment]
Hi @xx132917,
Please ensure you have no issues with your internet connection.
This happens if you can't reach the following files : 
https://raw.githubusercontent.com/wapiti-scanner/nikto/master/program/databases/db_tests
https://raw.githubusercontent.com/wapiti-scanner/wappalyzer/master/src/technologies.json

**Comment by devl00p** [comment]
Those files aren't directly included in Wapiti for licenses reasons but you can also download and copy them manually into your `~/.wapiti/config/ folder`.

I'm closing the issue as I guess it is a network issue.
